### ISSUE TITLE
Hand over more lifecycle functions to delegates

### ISSUE THREAD

**Issue by BraunreutherA** [sockeqwe/AdapterDelegates#17]
Actually only the adapter lifecycle functions for creation and bindings are supported. Would it be an option to add more?
``` java
public void onBindViewHolder(@NonNull T items, int position,
      @NonNull RecyclerView.ViewHolder viewHolder)
```
For example my case would be a callback when the view gets recycled for unbinding presenters.

**Comment by sockeqwe** [comment]
Not 100% sure about this. I would rather prefer to have the possibility to add a lifecycle listener to the ViewHolder, but obviously Adapter class is lacking this separation of concerns.

**Comment by BraunreutherA** [comment]
You could provide a Delegate as an easy to run solution. But the manager needs to pipe the events if the viewholder has a delegate.

**Comment by FabianShallari** [comment]
How about making the `delegates` and `fallbackDelegate` fields protected so that when someone needs extra lifecycle method propagations we can extend `AdapterDelegatesManager` and do things like: 

MyAdapter.java
```
public void onViewRecycled(RecyclerView.ViewHolder holder) {
      adapterDelegatesManager.onViewRecycled(holder)
}
```
MyAdapterDelegatesManager<T> extends AdapterDelegatesManager<T>

```
public void onViewRecycled(RecyclerView.ViewHolder viewHolder) {
    AdapterDelegate<T> delegate = super.delegates.get(viewHolder.getItemViewType());
    if (delegate == null) {
      if (fallbackDelegate == null) {
        throw new NullPointerException(
            "No AdapterDelegate added for ViewType " + viewHolder.getItemViewType());
      } else {
        delegate = fallbackDelegate;
      }
    }

    delegate.onViewRecycled(viewHolder);
  }
```

**Comment by sockeqwe** [comment]
Since version `2.0.1` there is a method `DelegatesManger.getDelegateForViewType()`

https://github.com/sockeqwe/AdapterDelegates/blob/master/library/src/main/java/com/hannesdorfmann/adapterdelegates2/AdapterDelegatesManager.java#L316

which returns, the registered delegate or the fallback delegate (if no registered delegate for the given view type). Otherwise, null (no delegate and no fallback set).

If you really need to know if the return AdapterDelegate is the Fallback delegate then you can use `AdapterDelegateManger.getFallbackDelegate()` and check if this is the same as returned from `DelegatesManger.getDelegateForViewType()`

https://github.com/sockeqwe/AdapterDelegates/blob/master/library/src/main/java/com/hannesdorfmann/adapterdelegates2/AdapterDelegatesManager.java#L335

**Comment by FabianShallari** [comment]
Thanks for the explanation @sockeqwe 👍  😃
