### ISSUE TITLE
AbsAdapterDelegate<T> extension from AnnotatedAdapter

### ISSUE THREAD

**Issue by ersin-ertan** [sockeqwe/AdapterDelegates#2]
## Part 01
After working with the lib right after working on AnnotatedAdapter, I asked myself the question "would there be any merit in having a class that looks something like:

```public abstract class AbsAdapterDelegate<T> ``` ***extends SupportAnnotatedAdapter***
```implements AdapterDelegate<T> {...}```

```public class Type00AdapterDelegate extends AbsAdapterDelegate<List<DisplayableItem>>```
***implements RecyclerListAdapterBinder***{...}

which would generate the 
```static class Type00ViewHolder extends RecyclerView.ViewHolder``` 

I think yes. The current implementation offers you the ability to use different delegates for different views, thus the model has a complimentary delegate class. To create a different view for the same model, you are required to create a new delegate class. 

By detecting the AnnotatedAdapter and combining its functionality with AdapterDelegates, you could now have multiple views displayed for one model, which would be useful for multi form factor development(Tv:largeViews, Wear:imageViews, mobile:ImageView and text, Tablet:large imageView, largeText and detail text...) or based on context(connected to WIFI:load character models into GLSurfaceView, 3G: grab images with Glide..., thematic/stylistic change)

## Part 02
After reading your annotations post, Butterknife groups annotation arguments as so:
```java
@Bind({ R.id.first_name, R.id.middle_name, R.id.last_name })
List<EditText> nameViews;

// translates to
@BindDelegates({AdAdapterDelegate, Type00AdapterDelegate, Type01AdapterDelegate})
private AdapterDelegatesManager<List<Viewable>> delegatesManager;

// or generalize with(not so sure about this one via implementation, but conceptually
// one would pass in a class that defines a group of delegates, allowing you to switch
// between them, or even pass in a new grouping)
@BindGroupings({AdapterDelegateGrouping00, AdapterDelegateGrouping01})
private AdapterDelegatesManager<List<Viewable>> delegatesManager;

public void setAdapterDelegate_Group/Single(AdapterDelegateGroup adg){
delegatesManager.setDelegate(adg);
}
public void addAdapterDelegate_Group/Single_ToCurrentSet(...){}
```
Showing only Reptiles with the Reptile delegate, by requiring a new list, or skipping elements that are not of that subtype.

**Comment by sockeqwe** [comment]
Thanks for sharing your thoughts!

**Part 1:**
Let's compare functionality of both libraries

Feature | AnnotatedAdapter | AdapterDelegates
-----------|--------------------------|-------------------------
ViewType "routing" | &#10003; | &#10003;
create / init view holder | &#10003; | &#10003;
bind view holder method | &#10003; | &#10003;
Generate ViewHolder class | &#10003; | missing

As you see the only feature `AnnotatedAdapter` currently has  implemented that `AdapterDelegate` doesn't have is the ability to generate `ViewHolder`. Therefore I don't see any need to extend from `SupportAnnotatedAdapter` since all features (except. ViewHolder generation) is already implemented in a clean and understandable way.  However,  it's legitimate to say we could just reuse the annotation processor from `AnnotatedAdapter`. Let me explain why I think that it's not a good idea: 
 1. You still have have to define `ViewHolder` classes manually. Instead of writing code you have to write annotations. What I really wanted to implement from the very beginning was that the xml layout `R.layout.my_item` gets processed and each view with an id should be part of the generated `ViewHolder`. `@ViewField` is just a workaround since it turned out that Annotation Processing has some limits when working with android, because it requires some extra annotation processing configuration: see https://github.com/sockeqwe/AnnotatedAdapter/issues/4 It's doable somehow, but maybe also needs some extra hacky workarounds to work properly.
 2. The limitation of annotation processing not be able to access directly an android resource ( like a xml layout) brings me to the conclusion that annotation processing is not the best choice for such a thing.
 3. In annotated Adapter the ViewHolder class is strongly tied into the library. You can not provide your own ViewHolder or extend from an generated ViewHolder. Thus you have to do some workarounds like `@Field` for including a `OnClickListener`. It's an ugly workaround.

Therefore I think a better solution for generating ViewHolders is to implement a Gradle plugin as it allows to read resources (xml layouts) easily and puts generated class into generated source folder as well. I think such a plugin will be a stand alone library / plugin (will not be part of AdapterDelegates). So instead of annotate you code, you have to mark your xml layout files somehow, i.e. by introducing a special xml tag like:
```xml
<FrameLayout >
     <viewholder classToGenerate="com.example.MyViewHolder" />
     <TextView />
</FrameLayout>
``` 
or as an attribute:
```xml
<FrameLayout 
      viewHolder:classToGenerate="com.example.MyViewHolder">

     <TextView />

</FrameLayout>
``` 


I think a gradle plugin can solve the problems described in `1.` `2.` `3.` As it will be a stand alone library / plugin the user can decide if he wants to use it in `AdapterDelegates` or not. Moreover, this plugin could be used without `AdapterDelegates`. I hope to find some time for that in September.


**Part2**
To be honest, I don't see any benefit by doing that with annotation processing. Most of the time you use annotation processing for generating boilerplate code. But I can't see any boilerplate code in: 
```java
@BindDelegates({AdAdapterDelegate.class, Type00AdapterDelegate.class, Type01AdapterDelegate.class})
private AdapterDelegatesManager<List<Viewable>> delegatesManager;
```
compared to "native code":
```java
delegatesManager.add(new AdAdapterDelegate())
                              .add(new Type00AdapterDelegate())
                              .add(new Type01AdapterDelegate());
```

Actually, I think the code gets harder to read and understand with annotations.
Therefore, no I have no plans to add such a annotation processor. 

However, if you think something like that is useful go ahead and write your own annotation processor for it.

**Comment by ersin-ertan** [comment]
I see, this has helped me better align my reasoning and motivations. Thanks for providing the walk-through, and the lead generation with regards to Gradle's plugin development. I think this calls for me to reinspect the libraries.
Cheers.
