### ISSUE TITLE
Method onBindViewHolder(RecyclerView.ViewHolder holder, int position) is never called

### ISSUE THREAD

**Issue by HD97300** [sockeqwe/AdapterDelegates#32]
Hi. After the issue #21 has been resolved, a 2 arg method will be never called by Android SDK, because we have already an overridden 3 arg method 
```java
public abstract class AbsDelegationAdapter<T> extends RecyclerView.Adapter {
//...
  @Override public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
    delegatesManager.onBindViewHolder(items, position, holder, null);
  }

  @Override
  public void onBindViewHolder(RecyclerView.ViewHolder holder, int position, List payloads) {
    delegatesManager.onBindViewHolder(items, position, holder, payloads);
  }
//...
}
```
So I can override this 2 arg method in my adapter and get no results. It's quite strange.

**Comment by sockeqwe** [comment]
Hm, stange.

Do you have a demo / example somewhere on github where I can take a look at?

**Comment by int-00h** [comment]
Adapter delegate will be work, because it will be call from the 3 arg method onBindViewHolder via delegatesManager.
But if I try to _add my own logic_ to AbsDelegationAdapter and override the 2 arg method, I get no results.
This happens because the Android SDK call only the 3 arg method (which call the 2 arg method on default). See yigit's https://github.com/sockeqwe/AdapterDelegates/pull/21#issuecomment-253865793
Since the AbsDelegationAdapter don't call the 2 arg method, nothing call it.
